apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fall-detection-hub.fullname" . }}-secret
  labels:
    {{- include "fall-detection-hub.labels" . | nindent 4 }}
type: Opaque
data:
  fhirMasterKey: {{ .Values.secret.fhirMasterKey | b64enc | quote }}
  cloudApiKey: {{ .Values.secret.cloudApiKey | b64enc | quote }}
