apiVersion: v1
kind: Service
metadata:
  name: {{ include "fall-detection-hub.fullname" . }}
  labels:
    {{- include "fall-detection-hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.csiUdpPort }}
      targetPort: csi-udp
      protocol: UDP
      name: csi-udp
    - port: {{ .Values.service.radarUdpPort }}
      targetPort: radar-udp
      protocol: UDP
      name: radar-udp
  selector:
    {{- include "fall-detection-hub.selectorLabels" . | nindent 4 }}
